### ISSUE TITLE
Custom plugin

### ISSUE THREAD

**Issue by PaulleDemon** [smilecc/react-easy-linkify#1]
Hi there, thank you for making this library. I wanted to know if you knew how to add a custom plugin. I wanted to linkify words starting with `s\`  do you know how I can achieve this, I tried looking into the plugin but I couldn't understand much as I am working with js and not typescript. Thank you.

**Edit**
I have decided to go with react-process-string https://www.npmjs.com/package/react-process-string library this easily allowed me to convert any string to text based on regex.

**Comment by smilecc** [comment]
so sorry, I've been too busy lately. I'm late to reply to you.
I understand you've found another way.

Good luck for you.
